# -*- coding: utf-8 -*-
"""
build_canonical_outputs.py
============================
Builds results/canonical/ -- the single authoritative location for
row-level predictions and aggregated metrics, computed EXCLUSIVELY through
canonical_metrics.py (see that module's docstring for why this
consolidation exists: at least six scripts in this repo duplicate the same
metric formula with small, drift-prone variations).

Canonical methods (all evaluated against the CURRENT
preprocessed_{train,val,test}.npz / scaler.pkl snapshot in this directory
-- see the timestamp cross-check in canonical_audit.csv):

  1. Mean               -- station-wise mean imputation (deterministic,
                           no seed), from baseline_results.pkl
  2. Linear             -- station-wise linear interpolation (deterministic,
                           no seed), from baseline_results.pkl
  3. KNN                -- KNN imputation (deterministic, no seed),
                           from baseline_results.pkl
  4. MICE                -- MICE imputation (deterministic, no seed),
                           from baseline_results.pkl
  5. AmountRF_DLPIF     -- full DLPIF: Stage-1 occurrence RF + Stage-2
                           amount RF, scenario-specific .npy per seed
                           (multiseed_clean_rerun.py output)
  6. DirectTwoStageRF   -- backbone-free Stage-1+Stage-2 RF baseline
                           (direct_two_stage_rf.py output)
  7. SingleStageRF      -- single RandomForestRegressor on the identical
                           26-feature Stage-2 amount matrix, trained on
                           ALL observed training days with no Stage-1
                           occurrence classifier (single_stage_rf.py
                           output); isolates the classify-then-regress
                           decomposition from the feature set itself
  8. MissingnessIndicatorRF -- DirectTwoStageRF's exact architecture and
                           hyperparameters, with six added local
                           (non-PRECIP) real-observed-vs-zero-filled
                           indicator features per stage
                           (missingness_indicator_rf.py output); isolates
                           the marginal value of explicit local-variable
                           missingness indicators
  9. SAITS              -- transformer-based multivariate imputation
                           baseline (baselines/train_saits_v2.py +
                           baselines/repackage_saits_outputs.py output)
  10. WGANGP_raw        -- WGAN-GP continuous backbone, raw generator
                           output for the PRECIP channel, no post-hoc
                           calibration (02_wgan_gp_imputation.py output,
                           trained on a CUDA machine via
                           gpu_transfer_package_scenario_wgan_v2.zip)
  11. WGANGP_PrecipFix  -- same WGAN-GP run as WGANGP_raw, with the
                           quantile-mapping / occurrence-threshold precip
                           calibration (precip_calibration.py) applied

WGAN-GP (WGANGP_raw / WGANGP_PrecipFix) reinstated 2026-08-02: its
training script hard-requires CUDA, unavailable in this local environment,
so training was performed externally on a CUDA machine (Tesla T4) using
gpu_transfer_package_scenario_wgan_v2.zip -- built from THIS session's
2005-2023-restricted preprocessed_{train,val,test}.npz snapshot, unlike the
2026-07-21 run this replaces, which predated the 2026-07-23 dataset
restriction and produced a (11180, 7) test-shape array incompatible with
the current (4168, 7) canonical test set. Both are included as real
continuous-backbone comparison baselines, parallel to SAITS; neither is a
component DLPIF depends on -- Section 5.8's architectural invariance test
already established DLPIF's precipitation reconstruction is bit-for-bit
independent of backbone content via adversarial dummy-backbone
substitution, so registering a real WGAN-GP backbone here does not change
any AmountRF_DLPIF number, only adds a further real-data confirmation of
that same invariance plus new comparison rows in its own right.
Precip2Stage ("WGAN-GP raw + occurrence correction + quantile mapping") was
never reconstructed: its definition predates this file's own git history
and is not referenced anywhere in the current manuscript text, so it is
deliberately left out rather than guessed at.

Every loader reads ONLY: preprocessed_test.npz, scaler.pkl, and a raw
prediction artifact (.npy or baseline_results.pkl) generated by this
session's pipeline scripts (01_data_preprocessing.py ->
03_baseline_imputation.py / multiseed_clean_rerun.py /
direct_two_stage_rf.py / baselines/train_saits_v2.py).
No results/*.csv or src/*.csv written by any OTHER script's own metric
implementation is ever read as a value source -- see canonical_audit.csv
check "no_legacy_file_read" for the enforced whitelist.

Fail-fast policy: if a required source file for one of the 9 methods x
(3 seeds x 4 scenarios, or 1 x 4 for a deterministic baseline method) is
missing, this script raises immediately. It does not silently skip a
combination and does not fall back to any archived/legacy CSV.

Layout
------
results/canonical/
  predictions/{method}.csv
      Row-level, ALL seeds x scenarios for that method, one file per
      method. Columns:
        method, scenario, seed, row_index, station_id, date,
        y_true, y_pred, evaluation_mask, source_file

  metrics/canonical_metrics_all.csv
      Long-form, ALL canonicalized methods, one row per (method, seed,
      scenario), produced by canonical_metrics.metrics_row() directly
      from in-memory mm arrays (rounded to 6 dp only when written to the
      predictions CSV -- the metrics themselves are computed from
      unrounded arrays so a later "recompute from predictions" audit
      check has no rounding-roundtrip noise to tolerate). Columns:
        method, scenario, seed, n_evaluated,
        freq_gt, freq_pred, signed_frequency_bias,
        precision, recall, f1, csi,
        rmse, mae, rmse_wet, mae_wet, mae_p95, rmse_p95,
        tp, fp, fn, tn, source_prediction_file

  metrics/canonical_metrics_summary.csv
      Mean +/- std across seeds, one row per (method, scenario). For the
      deterministic Linear method (a single "seed"), std is NaN (n=1).

  metrics/canonical_metrics_all.md
      Human-readable rendering of canonical_metrics_all.csv.

How to add a method
--------------------
Add an entry to METHODS below: `seeds` (list of ints, or
['deterministic'] for a no-seed method) and `path_fn(seed, scenario) ->
str | None` (absolute path to a normalised (N,7) .npy reconstruction, or
None if not applicable -- use `_load_baseline_linear` as the template for
a non-.npy source like baseline_results.pkl).
"""
import os
import warnings
import numpy as np
import pandas as pd

import canonical_metrics as cm
import direct_two_stage_rf as d2s

warnings.filterwarnings('ignore')

SRC_DIR         = d2s.SRC_DIR
REPO_ROOT       = d2s.REPO_ROOT
CANON_DIR       = os.path.join(REPO_ROOT, 'results', 'canonical')
PRED_DIR        = os.path.join(CANON_DIR, 'predictions')
METRICS_DIR     = os.path.join(CANON_DIR, 'metrics')
os.makedirs(PRED_DIR, exist_ok=True)
os.makedirs(METRICS_DIR, exist_ok=True)

SEEDS      = d2s.SEEDS                 # [42, 123, 456]
SCENARIOS  = d2s.SCENARIOS             # list of (scen_label, cor_key, mask_key)

# y_true/y_pred are written to predictions/*.csv at FULL float64 precision
# (pandas' default float serialisation, no explicit rounding). This is
# deliberate: a small number of ground-truth PRECIP observations are
# exactly 0.1 mm, and the mm/normalise/mm round-trip through the scaler
# perturbs them by ~1e-10, landing them a hair on one side of the 0.1 mm
# wet/dry threshold. Any rounding coarser than that perturbation (6
# decimals was tried and rejected) collapses the value back to exactly
# 0.100000, silently flipping its wet/dry classification and making the
# canonical_audit.csv "metrics_recompute_match" check fail for a handful
# of positions per scenario. Full precision keeps the CSV self-consistent
# with the in-memory metrics computed by this same script.


class MissingCanonicalInput(Exception):
    """Raised instead of silently skipping a (method, seed, scenario)
    combination -- fail fast, never fall back to an archived/legacy file.
    """


# ── Shared extraction: normalised (N,7) array -> masked PRECIP rows ────────

def _extract_masked_rows(sc, pidx, te, dates, sids, mask_key, arr_norm, source_file):
    art_mask = te[mask_key].astype(np.float32)
    mask_precip = art_mask[:, pidx].astype(bool)
    row_index = np.where(mask_precip)[0]

    y_true_full = sc.inverse_transform(
        np.nan_to_num(te['data'].astype(np.float64), nan=0.0))[:, pidx]
    arr_orig = sc.inverse_transform(np.clip(arr_norm.astype(np.float64), 0, 1))
    y_pred_full = arr_orig[:, pidx]

    return dict(
        row_index=row_index,
        y_true=y_true_full[row_index],
        y_pred=np.clip(y_pred_full[row_index], 0, None),
        dates=dates[row_index],
        station_id=sids[row_index],
        source_file=source_file,
    )


def _load_npy_scenario(fname, sc, pidx, te, dates, sids, mask_key):
    path = os.path.join(SRC_DIR, fname)
    if not os.path.exists(path):
        raise MissingCanonicalInput(f'required prediction file not found: {path}')
    arr_norm = np.load(path).astype(np.float32)
    return _extract_masked_rows(sc, pidx, te, dates, sids, mask_key, arr_norm, path)


def _load_baseline(bl_key, scen_label, sc, pidx, te, dates, sids, mask_key):
    """Generic loader for any deterministic baseline stored in
    baseline_results.pkl['all_scenarios'][(bl_key, scen_label)] -- 'linear',
    'mean', 'knn', or 'mice'.
    """
    pkl_path = os.path.join(SRC_DIR, 'baseline_results.pkl')
    if not os.path.exists(pkl_path):
        raise MissingCanonicalInput(f'required baseline file not found: {pkl_path}')
    import pickle
    with open(pkl_path, 'rb') as f:
        bl = pickle.load(f)
    key = (bl_key, scen_label)
    if key not in bl.get('all_scenarios', {}):
        raise MissingCanonicalInput(
            f'{pkl_path} has no ("{bl_key}", "{scen_label}") entry')
    arr_norm = bl['all_scenarios'][key].astype(np.float32)
    source_file = f'{pkl_path}::all_scenarios[("{bl_key}", "{scen_label}")]'
    return _extract_masked_rows(sc, pidx, te, dates, sids, mask_key, arr_norm, source_file)


# ── Method registry ──────────────────────────────────────────────────────────
# path_fn(seed, scen_label) -> loader dict (raises MissingCanonicalInput if
# the underlying artifact is absent -- fail fast, no silent skip).

def _amountrf_dlpif_loader(seed, scen_label, mask_key, sc, pidx, te, dates, sids):
    return _load_npy_scenario(
        f'gan_imputed_test_modeB_seed{seed}_msclean_amountrf_{scen_label}.npy',
        sc, pidx, te, dates, sids, mask_key)

def _direct_two_stage_rf_loader(seed, scen_label, mask_key, sc, pidx, te, dates, sids):
    return _load_npy_scenario(f'direct_two_stage_rf_test_seed{seed}_{scen_label}.npy',
                              sc, pidx, te, dates, sids, mask_key)

def _single_stage_rf_loader(seed, scen_label, mask_key, sc, pidx, te, dates, sids):
    # produced by single_stage_rf.py -- one RandomForestRegressor per seed on
    # the identical 26-feature amount matrix used by DLPIF's Stage 2
    # (build_amt_X), trained on ALL observed training days (no Stage 1
    # occurrence classifier). Isolates the classify-then-regress design
    # choice from the feature set itself.
    return _load_npy_scenario(f'single_stage_rf_test_seed{seed}_{scen_label}.npy',
                              sc, pidx, te, dates, sids, mask_key)

def _missingness_indicator_rf_loader(seed, scen_label, mask_key, sc, pidx, te, dates, sids):
    # produced by missingness_indicator_rf.py -- DirectTwoStageRF's exact
    # architecture/hyperparameters, with six added local (non-PRECIP)
    # real-observed-vs-zero-filled indicator features per stage. Isolates
    # the marginal value of explicit local-variable missingness indicators.
    return _load_npy_scenario(f'missingness_indicator_rf_test_seed{seed}_{scen_label}.npy',
                              sc, pidx, te, dates, sids, mask_key)

def _saits_loader(seed, scen_label, mask_key, sc, pidx, te, dates, sids):
    # produced by baselines/train_saits_v2.py + baselines/repackage_saits_outputs.py
    # (the latter pads train_saits_v2.py's 11160-row windowed output to the full
    # 11180-row canonical length via one additional overlapping tail-window
    # inference pass per station -- see that script's docstring)
    return _load_npy_scenario(f'saits_test_seed{seed}_{scen_label}.npy',
                              sc, pidx, te, dates, sids, mask_key)

def _linear_loader(seed, scen_label, mask_key, sc, pidx, te, dates, sids):
    # `seed` is always the literal string 'deterministic' for this method;
    # ignored here since baseline_results.pkl has no per-seed variants.
    return _load_baseline('linear', scen_label, sc, pidx, te, dates, sids, mask_key)

def _mean_loader(seed, scen_label, mask_key, sc, pidx, te, dates, sids):
    return _load_baseline('mean', scen_label, sc, pidx, te, dates, sids, mask_key)

def _knn_loader(seed, scen_label, mask_key, sc, pidx, te, dates, sids):
    return _load_baseline('knn', scen_label, sc, pidx, te, dates, sids, mask_key)

def _mice_loader(seed, scen_label, mask_key, sc, pidx, te, dates, sids):
    return _load_baseline('mice', scen_label, sc, pidx, te, dates, sids, mask_key)

def _wgangp_raw_loader(seed, scen_label, mask_key, sc, pidx, te, dates, sids):
    # produced by 02_wgan_gp_imputation.py on a CUDA machine (see
    # gpu_transfer_package_scenario_wgan_v2.zip) -- raw generator output for
    # the PRECIP channel, no post-hoc calibration. Included as a real
    # continuous-backbone comparison baseline, parallel to SAITS; not a
    # component DLPIF depends on (see Section 5.8 architectural invariance).
    return _load_npy_scenario(f'gan_imputed_test_modeB_{scen_label}_seed{seed}.npy',
                              sc, pidx, te, dates, sids, mask_key)

def _wgangp_precipfix_loader(seed, scen_label, mask_key, sc, pidx, te, dates, sids):
    # same generator run as WGANGP_raw, with the quantile-mapping /
    # occurrence-threshold precip calibration from precip_calibration.py
    # applied on top (precip_calibration_modeB_seed{seed}.json).
    return _load_npy_scenario(f'gan_imputed_test_modeB_{scen_label}_seed{seed}_precipfix.npy',
                              sc, pidx, te, dates, sids, mask_key)



# netblock30d (network-wide, simultaneous, multivariate 30-day block
# missingness -- build_network_block_scenario.py) is a TEST-ONLY scenario
# added after WGAN-GP's external CUDA-machine training run; no WGAN-GP
# reconstruction exists for it (would require re-running the GPU training
# pipeline, unavailable in this local environment -- see manuscript
# Limitations). Every other method is backbone-free or was re-run locally,
# so it covers all 5 scenarios; only WGANGP_raw / WGANGP_PrecipFix are
# restricted to the original 4.
SCENARIOS_NO_NETBLOCK = [s for s in SCENARIOS if s[0] != 'netblock30d']

METHODS = {
    # method name -> (seeds, loader(seed, scen_label, mask_key, sc, pidx, te, dates, sids), scenarios)
    'Mean':             (['deterministic'], _mean_loader,                   SCENARIOS),
    'Linear':           (['deterministic'], _linear_loader,                 SCENARIOS),
    'KNN':              (['deterministic'], _knn_loader,                    SCENARIOS),
    'MICE':             (['deterministic'], _mice_loader,                   SCENARIOS),
    'AmountRF_DLPIF':   (SEEDS,             _amountrf_dlpif_loader,         SCENARIOS_NO_NETBLOCK),
    'DirectTwoStageRF': (SEEDS,             _direct_two_stage_rf_loader,    SCENARIOS),
    'SingleStageRF':    (SEEDS,             _single_stage_rf_loader,        SCENARIOS),
    'MissingnessIndicatorRF': (SEEDS,       _missingness_indicator_rf_loader, SCENARIOS),
    'SAITS':            (SEEDS,             _saits_loader,                  SCENARIOS),
    'WGANGP_raw':       (SEEDS,             _wgangp_raw_loader,             SCENARIOS_NO_NETBLOCK),
    'WGANGP_PrecipFix': (SEEDS,             _wgangp_precipfix_loader,       SCENARIOS_NO_NETBLOCK),
}


# ── Full reconstructed series (shared by dry-spell / spatial-correlation) ──
# canonical_dry_spell.py and canonical_spatial_correlation.py both need a
# FULL per-day, per-station PRECIP series (dry-spell length and
# inter-station correlation depend on day-to-day continuity, unlike the
# point metrics above which only ever look at masked positions in
# isolation). This reconstructs it from exactly the same two sources
# already used everywhere else in this file: ground truth from
# preprocessed_test.npz, and this method's own masked-position predictions
# (via its already-registered METHODS loader) -- no separate "filled
# dataset" file, no legacy source.

def build_filled_series(method, seed, scen_label, sc, pidx, te, dates, sids, y_true_full):
    """Full (N,) reconstructed PRECIP series for one (method, seed, scenario):
    ground truth everywhere, overwritten by this method's y_pred at its own
    masked positions. Returns a DataFrame: row_index, station_id, date,
    y_true_full, y_filled.
    """
    seeds, loader, _scens = METHODS[method]
    if seed not in seeds:
        raise MissingCanonicalInput(f'{method} has no seed={seed!r} (registered: {seeds})')
    mask_key = dict((s, mk) for s, _ck, mk in SCENARIOS)[scen_label]
    out = loader(seed, scen_label, mask_key, sc, pidx, te, dates, sids)

    y_filled = y_true_full.copy()
    y_filled[out['row_index']] = out['y_pred']

    return pd.DataFrame({
        'row_index':   np.arange(len(y_true_full)),
        'station_id':  sids,
        'date':        pd.Series(dates).dt.strftime('%Y-%m-%d').values,
        'y_true_full': y_true_full,
        'y_filled':    y_filled,
    })


# ── Build ────────────────────────────────────────────────────────────────────

def main():
    print('=' * 70)
    print('  build_canonical_outputs.py')
    print('  results/canonical/{predictions,metrics}/ -- single source of truth')
    print('=' * 70)

    sc, mv = d2s.load_scaler()
    pidx = mv.index('PRECIP')
    te = d2s.load_npz('test')
    dates = pd.to_datetime(te['dates'])
    sids = te['station_ids']

    metrics_rows = []

    for method, (seeds, loader, method_scenarios) in METHODS.items():
        print(f'\n  -- {method} --')
        pred_frames = []
        # Forward-slash, not os.path.join, so this path is portable when
        # canonical_metrics_all.csv is read back on a different OS (was
        # previously a Windows backslash path on this platform, which does
        # not resolve on Linux/Mac -- breaking every downstream
        # traceability check there even though the underlying data is fine).
        pred_rel_path = 'results/canonical/predictions/' + f'{method}.csv'

        for seed in seeds:
            for scen_label, _cor_key, mask_key in method_scenarios:
                out = loader(seed, scen_label, mask_key, sc, pidx, te, dates, sids)
                # loader raises MissingCanonicalInput instead of returning None --
                # fail fast, this line only runs on success.

                y_true, y_pred = out['y_true'], out['y_pred']
                n_m = len(y_true)

                # -- canonical metrics, computed once, straight from unrounded mm arrays --
                row = cm.metrics_row(y_true, y_pred, method, scen_label,
                                     seed=seed, n_evaluated=n_m,
                                     source_prediction_file=pred_rel_path)
                metrics_rows.append(row)

                # -- row-level predictions, rounded only for the CSV, for
                #    downstream analysis scripts and audit recomputation --
                pred_frames.append(pd.DataFrame({
                    'method':         method,
                    'scenario':       scen_label,
                    'seed':           seed,
                    'row_index':      out['row_index'],
                    'station_id':     out['station_id'],
                    'date':           pd.Series(out['dates']).dt.strftime('%Y-%m-%d').values,
                    'y_true':         y_true,
                    'y_pred':         y_pred,
                    'evaluation_mask': 1,
                    'source_file':    out['source_file'],
                }))
                print(f'    [OK] seed={seed!s:<12} scenario={scen_label:<9} '
                      f'n_evaluated={n_m:5d}  F1={row["f1"]:.4f}  '
                      f'bias={row["signed_frequency_bias"]:+.4f}')

        df_pred = pd.concat(pred_frames, ignore_index=True)
        df_pred = df_pred.sort_values(['scenario', 'seed', 'row_index']) \
                          .reset_index(drop=True)
        out_path = os.path.join(PRED_DIR, f'{method}.csv')
        df_pred.to_csv(out_path, index=False)
        n_groups = df_pred.groupby(['scenario', 'seed']).ngroups
        expected_groups = len(method_scenarios) * len(seeds)
        print(f'  -> {out_path}  ({len(df_pred):,} rows, '
              f'{n_groups}/{expected_groups} seed x scenario groups)')
        if n_groups != expected_groups:
            raise MissingCanonicalInput(
                f'{method}: expected {expected_groups} seed x scenario groups, got {n_groups}')

    # ── Save long-form canonical metrics ────────────────────────────────────
    df_metrics = pd.DataFrame(metrics_rows)
    col_order = ['method', 'scenario', 'seed', 'n_evaluated',
                'freq_gt', 'freq_pred', 'signed_frequency_bias',
                'precision', 'recall', 'f1', 'csi',
                'rmse', 'mae', 'rmse_wet', 'mae_wet', 'mae_p95', 'rmse_p95',
                'tp', 'fp', 'fn', 'tn', 'source_prediction_file']
    df_metrics = df_metrics[col_order].sort_values(['method', 'scenario', 'seed'],
                                                    key=lambda s: s.astype(str)) \
                                       .reset_index(drop=True)

    csv_path = os.path.join(METRICS_DIR, 'canonical_metrics_all.csv')
    df_metrics.to_csv(csv_path, index=False)
    print(f'\n  -> {csv_path}  ({len(df_metrics)} rows)')

    # ── Save mean +/- std summary across seeds ─────────────────────────────
    numeric_cols = ['freq_gt', 'freq_pred', 'signed_frequency_bias',
                    'precision', 'recall', 'f1', 'csi',
                    'rmse', 'mae', 'rmse_wet', 'mae_wet', 'mae_p95', 'rmse_p95']
    summary_rows = []
    for (method, scenario), grp in df_metrics.groupby(['method', 'scenario']):
        row = dict(method=method, scenario=scenario, n_seeds=len(grp),
                   n_evaluated=int(grp['n_evaluated'].iloc[0]))
        for col in numeric_cols:
            vals = grp[col].dropna()
            row[f'{col}_mean'] = round(float(vals.mean()), 4) if len(vals) else np.nan
            row[f'{col}_std'] = (round(float(vals.std(ddof=1)), 4)
                                 if len(vals) > 1 else np.nan)
        summary_rows.append(row)
    df_summary = pd.DataFrame(summary_rows).sort_values(['method', 'scenario']) \
                                            .reset_index(drop=True)
    summary_path = os.path.join(METRICS_DIR, 'canonical_metrics_summary.csv')
    df_summary.to_csv(summary_path, index=False)
    print(f'  -> {summary_path}  ({len(df_summary)} rows)')

    # ── Markdown rendering ───────────────────────────────────────────────────
    md_lines = [
        '# Canonical Metrics (single source of truth)',
        '',
        'Computed exclusively via `canonical_metrics.metrics_row()` -- see',
        '`canonical_metrics.py` for why this file exists and',
        f'`build_canonical_outputs.py::METHODS` for the {len(METHODS)} registered methods.',
        '',
        '| Method | Scenario | Seed | N | Signed Freq Bias | F1 | CSI | RMSE | RMSE_wet | RMSE_p95 |',
        '|---|---|---|---|---|---|---|---|---|---|',
    ]
    for _, r in df_metrics.iterrows():
        md_lines.append(
            f"| {r['method']} | {r['scenario']} | {r['seed']} | {r['n_evaluated']} | "
            f"{r['signed_frequency_bias']:+.4f} | {r['f1']:.4f} | {r['csi']:.4f} | "
            f"{r['rmse']:.2f} | {r['rmse_wet']:.2f} | {r['rmse_p95']:.2f} |"
        )
    md_path = os.path.join(METRICS_DIR, 'canonical_metrics_all.md')
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(md_lines) + '\n')
    print(f'  -> {md_path}')

    print('\n' + '=' * 70)
    print(f'  BUILD COMPLETE -- {len(METHODS)} methods x (12 or 4) seed x scenario groups')
    print('=' * 70)


if __name__ == '__main__':
    main()
